services:
  web:
    image: nginx:latest
    ports:
      - "8082:80"
    volumes:
      - ./nginx_conf/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: compose_test-backend-1
    ports:
      - "8083:5000"

  assistant:
    build: ./assistant
    container_name: compose_test-assistant-1
    environment:
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - web
      - backend
