services:
  backend:
    build: .
    ports:
      - "5001:5000"

  web:
    image: nginx:latest
    ports:
      - "8083:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  assistant:
    build: ./assistant
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - web
      - backend

