name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Verify Docker and Compose
      run: |
        docker --version
        docker compose version

    - name: Build and start containers
      run: |
        docker compose up -d --build
        docker ps -a

    - name: Run smoke test
      run: |
        for i in {1..5}; do
          curl -f http://localhost:8082 && exit 0
          echo "Waiting for service..."
          sleep 5
        done
        exit 1

    - name: Stop containers
      if: always()
      run: docker compose down

    - name: Notify Slack
      if: always()
      run: |
        curl -X POST -H 'Content-type: application/json' \
        --data "{\"text\":\"CI result for $GITHUB_REPOSITORY on $GITHUB_REF_NAME: ${{ job.status }}\"}" \
        $SLACK_WEBHOOK_URL
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
